/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sushi.zen.interfacesGraficas.jinternalframe;

import br.sushi.zen.auxiliares.Relatorio;
import static br.sushi.zen.auxiliares.Relatorio.gerarRelatorio;
import br.sushi.zen.interfacesGraficas.frames.JanelaPrincipal;
import br.sushi.zen.interfacesGraficas.frames.jFCarregando;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Cesar Schutz
 */
public class RelatoriosPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatoriosPedidos
     */
    public RelatoriosPedidos() {
        super("Relatório de Pedidos", true, true, false, true);
        initComponents();
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroPedidos.png")));

        jDDataInicial.setFormats(new String[]{"E dd/MM/yyyy"});
        jDDataInicial.setLinkDate(System.currentTimeMillis(), "Hoje");

        jDDataFinal.setFormats(new String[]{"E dd/MM/yyyy"});
        jDDataFinal.setLinkDate(System.currentTimeMillis(), "Hoje");
    }

    @Override
    public void doDefaultCloseAction() {
        JanelaPrincipal.internalFrameRelatoriosPedidos.dispose();
        JanelaPrincipal.internalFrameRelatoriosPedidos = null;
    }

    public void botaoGerarRelatorio() {
        //pega as datas
        SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        Date dataInicial = jDDataInicial.getDate();
        String dataInicialString = df.format(dataInicial);

        Date dataFinal = jDDataFinal.getDate();
        String dataFinalString = df.format(dataFinal);

        //pega o caminho 
        JFileChooser fc = new JFileChooser();
        fc.setApproveButtonText("Salvar");
        fc.setDialogTitle("Selecione a Pasta");
        fc.setSelectedFile(new File("C:\\Relatorio de Pedidos"));

        int res = fc.showOpenDialog(null);
        String arquivoPDF;

        if (res == JFileChooser.APPROVE_OPTION) {
            File diretorio = fc.getSelectedFile();
            //return diretorio.getName();
            arquivoPDF = diretorio.getAbsolutePath() + ".pdf";
            
            //gera o relatorio
            Relatorio.main(new String[]{arquivoPDF, "sushiZenPedidos.jasper", dataInicialString, dataFinalString, "Gerando Relatório de Pedidos. Aguarde!"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDDataInicial = new org.jdesktop.swingx.JXDatePicker();
        jDDataFinal = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jBGerarRelatorio = new javax.swing.JButton();

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jBGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/imagemBotaoOk.png"))); // NOI18N
        jBGerarRelatorio.setText("Gerar Relatório");
        jBGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jDDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jDDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBGerarRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGerarRelatorio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jBGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarRelatorioActionPerformed
        botaoGerarRelatorio();
    }//GEN-LAST:event_jBGerarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerarRelatorio;
    public org.jdesktop.swingx.JXDatePicker jDDataFinal;
    public org.jdesktop.swingx.JXDatePicker jDDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
