package br.sushi.zen.interfacesGraficas.frames;

import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroCategoria_gasto;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroCategoria_gastoVisualizar;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroClienteVisualizar;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroProduto;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroCliente;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroForma_de_pagamento;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroForma_de_pagamentoVisualizar;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroGasto;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroGastosVisualizar;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroPedido;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroPedidoVisualizar;
import br.sushi.zen.interfacesGraficas.jinternalframe.CadastroProdutoVisualizar;
import br.sushi.zen.interfacesGraficas.jinternalframe.RelatorioGastos;
import br.sushi.zen.interfacesGraficas.jinternalframe.RelatoriosPedidos;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.HeadlessException;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Cesar Schutz
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    public static JanelaPrincipal janelaPrincipal = new JanelaPrincipal();
    public static CadastroClienteVisualizar internalFrameCadastroClienteVisualizar = null;
    public static CadastroCliente internalFrameCadastroCliente = null;
    public static CadastroProdutoVisualizar internalFrameCadastroProdutoVisualizar = null;
    public static CadastroProduto internalFrameCadastroProduto = null;
    public static CadastroPedidoVisualizar internalFrameCadastroPedidoVisualizar = null;
    public static CadastroPedido internalFrameCadastroPedido = null;
    public static CadastroGastosVisualizar internalFrameCadastroGastoVisualizar = null;
    public static CadastroGasto internalFrameCadastroGasto = null;
    public static CadastroForma_de_pagamentoVisualizar internalFrameCadastroForma_de_pagamentoVisualizar = null;
    public static CadastroForma_de_pagamento internalFrameCadastroForma_de_pagamento = null;
    public static CadastroCategoria_gastoVisualizar internalFrameCadastroCategoria_gastoVisualizar = null;
    public static CadastroCategoria_gasto internalFrameCadastroCategoria_gasto = null;
    public static RelatoriosPedidos internalFrameRelatoriosPedidos = null;
    public static RelatorioGastos internalFrameRelatorioGastos = null;

    public JMenuItem menuCarregando = new JMenuItem();
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/logo.png")).getImage());
        
        jDesktopPane1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                //aqui vai o que quero que aconteça quando mecher no tamanho do jdesktoppane
                //pega todos os jinternalframes do jdesktoppane
                JInternalFrame[] iframes = jDesktopPane1.getAllFrames();
                //percorrendo todos os jinternalframes pegos
                for (JInternalFrame iframe : iframes) {
                    //se jinternalframe estiver aberto, vai ser centralizado
                    if (iframe.isVisible()) {
                        //centralizando jinternalframe

                        int lDesk = jDesktopPane1.getWidth();
                        int aDesk = jDesktopPane1.getHeight();
                        int lIFrame = iframe.getWidth();
                        int aIFrame = iframe.getHeight();

                        iframe.setLocation(lDesk / 2 - lIFrame / 2, aDesk / 2 - aIFrame / 2);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMICadastroClientes = new javax.swing.JMenuItem();
        jMICadastroProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMICadastroGastos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMICadastroPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIRelatoriosPedidos = new javax.swing.JMenuItem();
        jMIRelatoriosGastos = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sushi Zen Delivery");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastro.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        jMICadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroClientes.png"))); // NOI18N
        jMICadastroClientes.setText("Clientes");
        jMICadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMICadastroClientes);

        jMICadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroProdutos.png"))); // NOI18N
        jMICadastroProdutos.setText("Produtos");
        jMICadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMICadastroProdutos);
        jMenu1.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroFormas_de_pagamento.png"))); // NOI18N
        jMenuItem2.setText("Formas de Pagamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroGastos.png"))); // NOI18N
        jMenu5.setText("Gastos");

        jMICadastroGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroGastos.png"))); // NOI18N
        jMICadastroGastos.setText("Gastos");
        jMICadastroGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroGastosActionPerformed(evt);
            }
        });
        jMenu5.add(jMICadastroGastos);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroCategorias_gasto.png"))); // NOI18N
        jMenuItem3.setText("Categorias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuAtedimento.png"))); // NOI18N
        jMenu4.setText("Atendimento");

        jMICadastroPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroPedidos.png"))); // NOI18N
        jMICadastroPedidos.setText("Pedidos");
        jMICadastroPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroPedidosActionPerformed(evt);
            }
        });
        jMenu4.add(jMICadastroPedidos);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuRelatorios.png"))); // NOI18N
        jMenu3.setText("Relatórios");

        jMIRelatoriosPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroPedidos.png"))); // NOI18N
        jMIRelatoriosPedidos.setText("Pedidos");
        jMIRelatoriosPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatoriosPedidosActionPerformed(evt);
            }
        });
        jMenu3.add(jMIRelatoriosPedidos);

        jMIRelatoriosGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sushi/zen/imagens/menuCadastroGastos.png"))); // NOI18N
        jMIRelatoriosGastos.setText("Gastos");
        jMIRelatoriosGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatoriosGastosActionPerformed(evt);
            }
        });
        jMenu3.add(jMIRelatoriosGastos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(835, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * abre um internalFrame.
     *
     * @param internalFrame
     */
    public static void abrirInternalFrame(JInternalFrame internalFrame) {
        jDesktopPane1.add(internalFrame);
        internalFrame.setVisible(true);
        centralizarInternalFrame(internalFrame);
    }

    /**
     * Centraliza o internalFrame.
     *
     * @param internalFrame
     */
    public static void centralizarInternalFrame(JInternalFrame internalFrame) {
        int lDesk = jDesktopPane1.getWidth();
        int aDesk = jDesktopPane1.getHeight();
        int lIFrame = internalFrame.getWidth();
        int aIFrame = internalFrame.getHeight();

        internalFrame.setLocation(lDesk / 2 - lIFrame / 2, aDesk / 2 - aIFrame / 2);
    }

    public static void internalFrameNaFrente(JInternalFrame internalFrame) {
        internalFrame.toFront();
        internalFrame.requestFocusInWindow();
    }

    private void jMICadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroClientesActionPerformed
        if (internalFrameCadastroClienteVisualizar == null && internalFrameCadastroCliente == null) {
            internalFrameCadastroClienteVisualizar = new CadastroClienteVisualizar();
            abrirInternalFrame(internalFrameCadastroClienteVisualizar);
        } else if (internalFrameCadastroCliente != null) {
            centralizarInternalFrame(internalFrameCadastroCliente);
            internalFrameNaFrente(internalFrameCadastroCliente);
        } else if (internalFrameCadastroClienteVisualizar != null) {
            centralizarInternalFrame(internalFrameCadastroClienteVisualizar);
            internalFrameNaFrente(internalFrameCadastroClienteVisualizar);
        }
    }//GEN-LAST:event_jMICadastroClientesActionPerformed

    private void jMICadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroProdutosActionPerformed

        if (internalFrameCadastroProdutoVisualizar == null && internalFrameCadastroProduto == null) {
            internalFrameCadastroProdutoVisualizar = new CadastroProdutoVisualizar();
            abrirInternalFrame(internalFrameCadastroProdutoVisualizar);
        } else if (internalFrameCadastroProduto != null) {
            centralizarInternalFrame(internalFrameCadastroProduto);
            internalFrameNaFrente(internalFrameCadastroProduto);
        } else if (internalFrameCadastroProdutoVisualizar != null) {
            centralizarInternalFrame(internalFrameCadastroProdutoVisualizar);
            internalFrameNaFrente(internalFrameCadastroProdutoVisualizar);
        }

    }//GEN-LAST:event_jMICadastroProdutosActionPerformed

    private void jMICadastroPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroPedidosActionPerformed

        if (internalFrameCadastroPedidoVisualizar == null && internalFrameCadastroPedido == null) {
            internalFrameCadastroPedidoVisualizar = new CadastroPedidoVisualizar();
            abrirInternalFrame(internalFrameCadastroPedidoVisualizar);
        } else if (internalFrameCadastroPedido != null) {
            centralizarInternalFrame(internalFrameCadastroPedido);
            internalFrameNaFrente(internalFrameCadastroPedido);
        } else if (internalFrameCadastroPedidoVisualizar != null) {
            centralizarInternalFrame(internalFrameCadastroPedidoVisualizar);
            internalFrameNaFrente(internalFrameCadastroPedidoVisualizar);
        }

    }//GEN-LAST:event_jMICadastroPedidosActionPerformed

    private void jMICadastroGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroGastosActionPerformed
        if (internalFrameCadastroGastoVisualizar == null && internalFrameCadastroGasto == null) {
            internalFrameCadastroGastoVisualizar = new CadastroGastosVisualizar();
            abrirInternalFrame(internalFrameCadastroGastoVisualizar);
        } else if (internalFrameCadastroGasto != null) {
            centralizarInternalFrame(internalFrameCadastroGasto);
            internalFrameNaFrente(internalFrameCadastroGasto);
        } else if (internalFrameCadastroGastoVisualizar != null) {
            centralizarInternalFrame(internalFrameCadastroGastoVisualizar);
            internalFrameNaFrente(internalFrameCadastroGastoVisualizar);
        }
    }//GEN-LAST:event_jMICadastroGastosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (internalFrameCadastroForma_de_pagamentoVisualizar == null && internalFrameCadastroForma_de_pagamento == null) {
            internalFrameCadastroForma_de_pagamentoVisualizar = new CadastroForma_de_pagamentoVisualizar();
            abrirInternalFrame(internalFrameCadastroForma_de_pagamentoVisualizar);
        } else if (internalFrameCadastroForma_de_pagamento != null) {
            centralizarInternalFrame(internalFrameCadastroForma_de_pagamento);
            internalFrameNaFrente(internalFrameCadastroForma_de_pagamento);
        } else if (internalFrameCadastroForma_de_pagamentoVisualizar != null) {
            centralizarInternalFrame(internalFrameCadastroForma_de_pagamentoVisualizar);
            internalFrameNaFrente(internalFrameCadastroForma_de_pagamentoVisualizar);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (internalFrameCadastroCategoria_gastoVisualizar == null && internalFrameCadastroCategoria_gasto == null) {
            internalFrameCadastroCategoria_gastoVisualizar = new CadastroCategoria_gastoVisualizar();
            abrirInternalFrame(internalFrameCadastroCategoria_gastoVisualizar);
        } else if (internalFrameCadastroCategoria_gasto != null) {
            centralizarInternalFrame(internalFrameCadastroCategoria_gasto);
            internalFrameNaFrente(internalFrameCadastroCategoria_gasto);
        } else if (internalFrameCadastroCategoria_gastoVisualizar != null) {
            centralizarInternalFrame(internalFrameCadastroCategoria_gastoVisualizar);
            internalFrameNaFrente(internalFrameCadastroCategoria_gastoVisualizar);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMIRelatoriosPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatoriosPedidosActionPerformed
        if (internalFrameRelatoriosPedidos == null) {
            internalFrameRelatoriosPedidos = new RelatoriosPedidos();
            abrirInternalFrame(internalFrameRelatoriosPedidos);
        } else {
            internalFrameNaFrente(internalFrameRelatoriosPedidos);
        }
    }//GEN-LAST:event_jMIRelatoriosPedidosActionPerformed

    private void jMIRelatoriosGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatoriosGastosActionPerformed
        if (internalFrameRelatorioGastos == null) {
            internalFrameRelatorioGastos = new RelatorioGastos();
            abrirInternalFrame(internalFrameRelatorioGastos);
        } else {
            internalFrameNaFrente(internalFrameRelatorioGastos);
        }
    }//GEN-LAST:event_jMIRelatoriosGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (criarJoptionPaneParaDefinirNovoValorDoProduto()) {
                    JanelaPrincipal.janelaPrincipal = new JanelaPrincipal();
                    JanelaPrincipal.janelaPrincipal.setVisible(true);
                } else {
                }
            }
        });
    }

    public static boolean criarJoptionPaneParaDefinirNovoValorDoProduto() {
        // Cria campo onde o usuario entra com a senha 
        final JTextField textField = new JPasswordField();
        Dimension tamanhoDoTextField = new Dimension(120, 30);
        textField.setPreferredSize(tamanhoDoTextField);
        textField.setMinimumSize(tamanhoDoTextField);
        textField.setMaximumSize(tamanhoDoTextField);

        textField.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent ce) {
                textField.requestFocusInWindow();
            }
        });

        // Cria um rótulo para o campo  
        JLabel rotulo = new JLabel("Senha: ");

        // Coloca o rótulo e a caixa de entrada numa JPanel:  
        JPanel entUsuario = new JPanel();
        entUsuario.add(rotulo);
        entUsuario.add(textField);

        // Mostra o rótulo e a caixa de entrada de password para o usuario fornecer a senha:  
        int intRetornado = JOptionPane.showConfirmDialog(JanelaPrincipal.janelaPrincipal, entUsuario, "Login", JOptionPane.PLAIN_MESSAGE);
        textField.requestFocusInWindow();
        if (intRetornado == 0) {
            try {
                if (Integer.valueOf(textField.getText()) == 112222334) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "senha inválida, tente novamente!");
                    criarJoptionPaneParaDefinirNovoValorDoProduto();
                    return false;
                }
            } catch (NumberFormatException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Senha Inválida. Tente novamente!", "Atenção!", JOptionPane.WARNING_MESSAGE);
                criarJoptionPaneParaDefinirNovoValorDoProduto();
                return false;
            }

        } else {
            System.exit(0);
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMICadastroClientes;
    private javax.swing.JMenuItem jMICadastroGastos;
    private javax.swing.JMenuItem jMICadastroPedidos;
    private javax.swing.JMenuItem jMICadastroProdutos;
    private javax.swing.JMenuItem jMIRelatoriosGastos;
    private javax.swing.JMenuItem jMIRelatoriosPedidos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
